language: node_js
node_js:
  - 14
env:
  - EXTENSION_ID='lmjdlojahmbbcodnpecnjnmlddbkjhnn'
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      # On cron jobs https://docs.travis-ci.com/user/cron-jobs/
      # When clicking "Trigger build" https://blog.travis-ci.com/2017-08-24-trigger-custom-build
      branch: master
      condition: (($TRAVIS_EVENT_TYPE = api) || ($TRAVIS_EVENT_TYPE = cron && $(git rev-list --since=yesterday HEAD)))
