name: Auto-tagger

on:
  schedule:
    - cron: '31 13 * * 3' # Every Wednesday at 13:31 https://crontab.guru/#31_13_*_*_3

jobs:
  create-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          if [[ $(git tag -l --points-at HEAD) = "" ]]; then
            export VER=$(npx daily-version)
            git tag $VER -m $VER
            git push origin $VER
          fi
